### ISSUE TITLE
module is not showing under apps menu

### ISSUE THREAD

**Issue by umarmeo** [YvanDotet/query_deluxe#14]
Hello,

I have uploaded files as per instructions and commit status is success. But I don't see query_deluxe in apps menu.

**Comment by YvanDotet** [comment]
Hello @umarmeo 
Thanks for your return.

In which version did you download the application ?

In fact the module create a group named 'Access query_deluxe' that is then added to the 'group_system' administrator's group of odoo.
So to be able to see that, you have to be inside the system's group ( or the 'Access query_deluxe' group is also ok ).

Then there are 1 menu that has been created called "Query Deluxe" that is used to access to the application. His sequence is "-1" so it normaly always appears on the top of application list.

Can you describe more about the situation ?

Thanks.

Sincerely,
Dotet Yvan.

**Comment by YvanDotet** [comment]
Dear @umaremo,
In the new version of query deluxe, the groups "base.group_system" and "base.group_erp_manager" can now give access to the menu of "query_deluxe".
