### ISSUE TITLE
Updates add all users of group_erp_manager

### ISSUE THREAD

**Issue by bertstomphorst** [YvanDotet/query_deluxe#31]
We love query_deluxe, but experience an issue when de module is updated: all members of `base.group_erp_manager` are added again to `query_deluxe.group_query_deluxe`. We've a user who is allowed to edit access-rights (because of creating new users), but not should have access to query_deluxe. 
Although this user could enable it for himself, that's no problem. Now it's confusing that 'out of the blue' there's an additional icon on the main menu.

Can you please mark those security-data as no-update (only on initial install of the module)?

**Comment by YvanDotet** [comment]
Dear Mr Stomphorst,
Thank you for your comment.

As I understand, you want to mark as 'no-update' the adding moment where the user from group 'group_erp_manager' is added to the "query deluxe" group ? 

By doing this, this will add the user only once, and then if you update de module query deluxe after modifications, it will not put him again on this group.

(Sorry for the delay of the answer) .

Sincerely.
Yvan.

**Comment by bertstomphorst** [comment]
Hi Yvan,
Yes, that's what I should expect.
Thank you,
Bert

**Comment by YvanDotet** [comment]
Ok it is a good idea because the security for this module is important with the possibility of doing sql request within the interface.

Thanks for you contribuation, I will add it.

I have just one another question : did you test this module on odoo sh ? Which version did you download ?

Thank you and have a good day.
Sincerely,
Yvan.

**Comment by bertstomphorst** [comment]
Hi Yvan,
Thanx! Yes, I'm using it on odoo.sh, linked as submodule, current version 16.0.1.0.5

**Comment by YvanDotet** [comment]
Ok thanks.
I ask this because someone else have telling me about an error on odoo sh, but if it's work it's ok.
https://github.com/YvanDotet/query_deluxe/issues/29

The new version with the modification is actually available "16.0.1.0.6".
https://apps.odoo.com/apps/modules/16.0/query_deluxe/

**Comment by bertstomphorst** [comment]
Ok, I'm on Odoo 15 not on 16. 

I've got the update today and works fine, thanx!
