### ISSUE TITLE
[SEC] Security Vulnerability in query_deluxe

### ISSUE THREAD

**Issue by luvsn** [YvanDotet/query_deluxe#36]
Hello,

I discovered a security vulnerability in your _query_deluxe_ module for Odoo. 
Is it possible to contact you by email to discuss about it?

Best regards,
L

**Comment by YvanDotet** [comment]
Dear Lucas,
Thanks you for your return.
Yes we can discuss about this on my email present in the Query deluxe module. : "yvandotet@yahoo.fr"

Sincerely.

@luvsn

**Comment by YvanDotet** [comment]
The error has been fixed.
Thanks for your collaboration.
